packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
